import styles from "Timeline.module.scss";
import Link from "next/link";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Timeline({ name }) {
  const router = useRouter();
  console.log(router);
  return (
    <div className={styles.container}>
      <Head>
        <title>Timeline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.p}>This is the timeline of {name}</h1>
      <Link href="/">Go Home</Link>
    </div>
  );
}

Timeline.getInitialProps = () => {
  return fetch("https://swapi.dev/api/people/1/").then((res) => res.json());
};
