import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Button from "../components/Button";
import GitHub from "../components/Icons/GitHub";
import { loginWithGitHub, onAuthStateChanged } from "../firebase/client";

export default function Home() {
  const [user, setUser] = useState(undefined);

  useEffect(() => {
    onAuthStateChanged(setUser);
  }, []);

  const handleClick = () => {
    loginWithGitHub().then(setUser);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter MVP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <Image
            src="/devter-logo.png"
            alt="Devter Logo"
            width={100}
            height={100}
          />
          <h1 className={styles.title}>Twitter MVP</h1>
          <h2 className={styles.title}>
            The new Twitter <br /> made by Next.js
          </h2>
          <div>
            {user === null && (
              <Button onClick={() => handleClick()}>
                <GitHub fill={"#fff"} width={24} height={24} />
                Login with GitHub
              </Button>
            )}

            {user && user.avatar && (
              <div>
                <Image
                  src={user.avatar}
                  alt="Avatar"
                  width={100}
                  height={100}
                />
                <strong>{user.username}</strong>
              </div>
            )}
          </div>

          {/* <nav className={styles.navbar}>
            <Link href="/timeline">Timeline</Link>
          </nav> */}
        </section>
      </main>
    </div>
  );
}
