import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "index.module.scss";
import Button from "components/Button";
import GitHub from "components/Icons/GitHub";
import { loginWithGitHub, onAuthStateChanged } from "../firebase/client";
import Avatar from "components/Avatar";
import Logo from "components/Icons/Logo";

export default function Home() {
  const [user, setUser] = useState(undefined);

  useEffect(() => {
    onAuthStateChanged(setUser);
  }, []);

  const handleClick = () => {
    loginWithGitHub(setUser);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter MVP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <Logo width="100" />
          <h1 className={styles.title}>Twitter MVP</h1>
          <h2 className={styles.title}>
            The new Twitter <br /> made by Next.js
          </h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub fill={"#fff"} width={24} height={24} />
                Login with GitHub
              </Button>
            )}

            {user && user.avatar && (
              <Avatar
                name={user.username}
                src={user.avatar}
                alt={"avatar"}
                withText
              />
            )}
          </div>

          {/* <nav className={styles.navbar}>
            <Link href="/timeline">Timeline</Link>
          </nav> */}
        </section>
      </main>
    </div>
  );
}
