import Devit from "components/Devit";
import Head from "next/head";
import { firestore } from "firebase/admin";
import { useRouter } from "next/router";

export default function DevitPage(props) {
  const router = useRouter();

  if (router.isFallback) return <h1>Cargando...</h1>;

  const sampleData = {
    sharedCount: 0,
    avatar: "https://avatars.githubusercontent.com/u/6982222?v=4",
    content: "otra prueba",
    userId: "IhpI1dDC4LQ9F2ADaEizx3AVqe53",
    likesCount: 0,
    createdAt: 1656232232381,
    userName: "Ignacio Mansilla Derqui",
    id: "wJZIETdiaIhzynnh8LNG",
  };

  return (
    <>
      <Head>
        <title>Devit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Devit {...(props || sampleData)} />
    </>
  );
}

export async function getStaticPaths() {
  return {
    paths: [{ params: { id: "wJZIETdiaIhzynnh8LNG" } }],
    fallback: true,
  };
}

export async function getStaticProps(context) {
  const { params } = context;
  const { id } = params;

  return firestore
    .collection("devits")
    .doc(id)
    .get()
    .then((doc) => {
      const data = doc.data();
      const id = doc.id;
      const { createdAt } = data;

      const props = {
        ...data,
        id,
        createdAt: +createdAt.toDate(),
      };
      console.log(props);
      return { props };
    })
    .catch(() => {
      return { props: {} };
    });
}
